"""
Handoff package export — Phase 4 (FR-11).

    POST /api/export/handoff
        body: { format: 'docx'|'md',
                board_name: str,
                artifacts: [ {folder, items:[ str |
                              {label, agent?, zone?, src?, by?, at?, body?} ]} ] }
        -> the assembled package as a file download.

The frontend sends its live artifact library (the same structure the
board persists). Items filed since Phase 2 carry provenance and, since
Phase 4, the approved draft's body HTML — those render as full sections;
older/seeded string items render as checklist lines.

DOCX is generated server-side with python-docx (real generation — the
old NaviCore approach was browser print-to-PDF; FR-11 requires an actual
.docx file). Markdown is the second format. PDF stays a UI option only,
deliberately unimplemented this phase.
"""

from __future__ import annotations

import io
import re
from datetime import date

from flask import Blueprint, jsonify, request, send_file

from app.auth import auth_required
from app.core.logging import log

bp = Blueprint('export', __name__)

# Package section order mirrors the Handoff modal / Master Documentation §14.
_FOLDER_ORDER = ['Background', 'How it works', 'Requirements',
                 'Issues & decisions', 'Meeting notes', 'Proposal']

_TAG_RE = re.compile(r'<[^>]+>')
_LI_RE = re.compile(r'<li[^>]*>(.*?)</li>', re.DOTALL)
_BR_RE = re.compile(r'<br\s*/?>', re.IGNORECASE)


def _html_to_blocks(body_html: str) -> list[tuple[str, str]]:
    """Very small HTML→blocks converter for the sanitised draft bodies:
    returns [('bullet'|'para', text), ...]."""
    if not body_html:
        return []
    blocks: list[tuple[str, str]] = []
    rest = body_html

    def _clean(s: str) -> str:
        s = _BR_RE.sub('\n', s)
        s = _TAG_RE.sub('', s)
        return re.sub(r'\n{2,}', '\n', s).strip()

    # Pull out list items in order; everything between/around lists is paragraphs.
    pos = 0
    for m in _LI_RE.finditer(body_html):
        before = body_html[pos:m.start()]
        before = re.sub(r'</?(ul|ol)[^>]*>', '', before)
        t = _clean(before)
        if t:
            blocks.append(('para', t))
        li = _clean(m.group(1))
        if li:
            blocks.append(('bullet', li))
        pos = m.end()
    tail = re.sub(r'</?(ul|ol)[^>]*>', '', body_html[pos:])
    t = _clean(tail)
    if t:
        blocks.append(('para', t))
    if not blocks:
        t = _clean(rest)
        if t:
            blocks = [('para', t)]
    return blocks


def _norm_items(artifacts: list) -> dict[str, list[dict]]:
    """{folder -> [{label, prov_line, body}]} in package order."""
    by_folder: dict[str, list[dict]] = {}
    for f in artifacts or []:
        folder = (f or {}).get('folder') or 'Other'
        for it in (f or {}).get('items') or []:
            if isinstance(it, str):
                rec = {'label': it, 'prov': '', 'body': ''}
            else:
                it = it or {}
                prov_bits = [b for b in [
                    ('agent ' + it['agent']) if it.get('agent') else '',
                    ('zone ' + it['zone']) if it.get('zone') else '',
                    ('approved by ' + it['by']) if it.get('by') else '',
                    it.get('at') or '',
                ] if b]
                rec = {'label': it.get('label') or 'Untitled',
                       'prov': ' · '.join(prov_bits),
                       'body': it.get('body') or ''}
            by_folder.setdefault(folder, []).append(rec)
    return by_folder


def _build_docx(board_name: str, by_folder: dict) -> io.BytesIO:
    from docx import Document
    from docx.shared import Pt, RGBColor

    doc = Document()
    doc.add_heading(board_name or 'AI Discovery Canvas — Handoff Package', level=0)
    p = doc.add_paragraph(f'Assembled from Live Artifacts · {date.today().isoformat()} '
                          '· generated by AI Discovery Canvas')
    p.runs[0].font.size = Pt(9)
    p.runs[0].font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

    folders = [f for f in _FOLDER_ORDER if f in by_folder] + \
              [f for f in by_folder if f not in _FOLDER_ORDER]
    for folder in folders:
        doc.add_heading(folder, level=1)
        for rec in by_folder[folder]:
            doc.add_heading(rec['label'], level=2)
            if rec['prov']:
                pr = doc.add_paragraph(rec['prov'])
                pr.runs[0].font.size = Pt(8)
                pr.runs[0].font.italic = True
                pr.runs[0].font.color.rgb = RGBColor(0x6B, 0x72, 0x80)
            for kind, text in _html_to_blocks(rec['body']):
                doc.add_paragraph(text, style='List Bullet' if kind == 'bullet' else None)
    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf


def _build_md(board_name: str, by_folder: dict) -> io.BytesIO:
    lines = [f'# {board_name or "AI Discovery Canvas — Handoff Package"}',
             f'_Assembled from Live Artifacts · {date.today().isoformat()}_', '']
    folders = [f for f in _FOLDER_ORDER if f in by_folder] + \
              [f for f in by_folder if f not in _FOLDER_ORDER]
    for folder in folders:
        lines.append(f'## {folder}')
        for rec in by_folder[folder]:
            lines.append(f'### {rec["label"]}')
            if rec['prov']:
                lines.append(f'_{rec["prov"]}_')
            for kind, text in _html_to_blocks(rec['body']):
                lines.append(('- ' + text) if kind == 'bullet' else text)
            lines.append('')
        lines.append('')
    return io.BytesIO('\n'.join(lines).encode('utf-8'))


@bp.route('/api/export/handoff', methods=['POST'])
@auth_required
def handoff():
    body = request.get_json(silent=True) or {}
    fmt = (body.get('format') or 'docx').lower()
    board_name = str(body.get('board_name') or '')[:120]
    by_folder = _norm_items(body.get('artifacts') or [])
    if not by_folder:
        return jsonify({'ok': False, 'error': 'no artifacts to export'}), 400
    try:
        if fmt == 'md':
            buf = _build_md(board_name, by_folder)
            return send_file(buf, as_attachment=True, download_name='handoff-package.md',
                             mimetype='text/markdown')
        if fmt == 'docx':
            buf = _build_docx(board_name, by_folder)
            return send_file(
                buf, as_attachment=True, download_name='handoff-package.docx',
                mimetype='application/vnd.openxmlformats-officedocument.wordprocessingml.document')
        return jsonify({'ok': False, 'error': f'format "{fmt}" not available (docx or md)'}), 400
    except Exception as e:
        log.warning('[EXPORT] handoff %s failed (%s): %s', fmt, e.__class__.__name__, e)
        return jsonify({'ok': False, 'error': f'export failed: {e}'}), 200


def install(app) -> None:
    app.register_blueprint(bp)
